src/Entity/Gift.php
<?php

namespace App\Entity;

use App\Repository\GiftRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;


#[ORM\Entity(repositoryClass: GiftRepository::class)]
#[Vich\Uploadable]
#[ORM\HasLifecycleCallbacks]

class Gift
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom = null;

    #[ORM\Column(nullable: true)]
    private ?float $prix = null;


    #[Vich\UploadableField(mapping: 'image_upload', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $imageName = null;

    #[ORM\Column(length: 800, nullable: true)]
    private ?string $lien_achat = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $status = null;

    #[ORM\ManyToOne(inversedBy: 'gifts')]
    private ?GiftList $GiftList = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(nullable: true)]
    private ?int $createdBy = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->updatedAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getLienAchat(): ?string
    {
        return $this->lien_achat;
    }

    public function setLienAchat(?string $lien_achat): static
    {
        $this->lien_achat = $lien_achat;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getGiftList(): ?GiftList
    {
        return $this->GiftList;
    }

    public function setGiftList(?GiftList $GiftList): static
    {
        $this->GiftList = $GiftList;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedBy(): ?int
    {
        return $this->createdBy;
    }

    public function setCreatedBy(int $createdBy): static
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    #[ORM\PreUpdate()]
    public function setUpdatedAtValue()
    {
        $this->updatedAt = new \DateTimeImmutable();
    }


    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): static
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }
}

src/Controller/Front/DefaultController.php
<?php

namespace App\Controller\Front;



use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    #[Route('/', name: 'app_default')]
    public function index(Request $request): Response
    {

        return $this->render('front/home.html.twig', [
        ]);
    }

    #[Route('/termine', name: 'app_default_finish')]
    public function test(Request $request): Response
    {
        return $this->render('front/default/finish.html.twig');
    }
}

src/Controller/Front/GiftController.php
<?php

namespace App\Controller\Front;

use Goutte\Client;
use App\Entity\Gift;
use App\Form\GiftType;
use App\Entity\GiftList;
use App\Service\EmailService;
use App\Security\EmailVerifier;
use App\Repository\GiftRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\DomCrawler\Crawler;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Vich\UploaderBundle\Templating\Helper\UploaderHelper;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Routing\Generator\UrlGeneratorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use SymfonyCasts\Bundle\VerifyEmail\Exception\VerifyEmailExceptionInterface;


#[Route('/gift')]
class GiftController extends AbstractController
{
    private EmailVerifier $emailVerifier;
    private EmailService $emailService;

    public function __construct(EmailVerifier $emailVerifier, EmailService $emailService)
    {
        $this->emailVerifier = $emailVerifier;
        $this->emailService = $emailService;
    }


    #[Route('/', name: 'app_gift_index', methods: ['GET'])]
    public function index(GiftRepository $giftRepository, Security $security): Response
    {
        // Récupérez l'utilisateur connecté
        $user = $security->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login', [], Response::HTTP_SEE_OTHER);
        }
        if (in_array('ROLE_ADMIN', $user->getRoles())) {
            // Récupérez les cadeaux créés par l'utilisateur connecté
            // Utilisateur non connecté en tant qu'administrateur, affichez tous les cadeaux
            $gifts = $giftRepository->findAll();
        } else {

            $gifts = $giftRepository->findBy(['createdBy' => $user]);
        }


        return $this->render('front/gift/index.html.twig', [
            'gifts' => $giftRepository->findAll(),
        ]);
    }

    #[Route('/add-gift-via-link/{id}', name: 'add_gift_via_link', methods: ['GET', 'POST'])]
    public function addGiftViaLink(Request $request, EntityManagerInterface $entityManager, GiftList $giftList, SluggerInterface $slugger): Response
    {
        $gift = new Gift();
        $form = $this->createFormBuilder()
            ->add('lien', TextType::class, [
                'label' => 'Lien du cadeau',
                'attr' => ['placeholder' => 'Saisissez le lien du cadeau'],
            ])
            ->add(
                "name",
                null,
                [
                    'constraints' => [
                        new Assert\NotBlank([
                            'message' => "Le champ 'nom' ne peut pas être vide.",
                        ]),
                    ],
                ]
            )
            ->add('email', null, [
                'constraints' => [
                    new Assert\NotBlank([
                        'message' => "Le champ 'email' ne peut pas être vide.",
                    ]),
                    new Assert\Email([
                        'message' => "L'email '{{ value }}' n'est pas valide.",
                    ]),
                ],
            ])
            ->add('save', SubmitType::class, ['label' => 'Ajouter le cadeau'])
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // Récupérez le lien soumis par le formulaire
            $link = $form->get('lien')->getData();

            // Utilisez Goutte pour extraire les informations du lien
            $client = new Client();

            //verifiez que le lien est valide
            try {
                $crawler = $client->request('GET', $link);
            } catch (\Throwable $th) {
                // flash message
                $this->addFlash('danger', 'Le lien que vous avez saisi n\'est pas valide');
                return $this->redirectToRoute('front_add_gift_via_link', ['id' => $giftList->getId()]);
            }
            $crawler = $client->request('GET', $link);
            //dd($crawler);
            $imageUrl = '';
            $imgSrc = '';

            // Extrayez l'image du produit
            // Select the li elements by their CSS classes
            $liElements = $crawler->filter('ul.list-none.w-full li.list-none.w-full.flex.justify-center');
            //dd($liElements);
            $imgSrc = '';
            // Loop through the selected li elements
            $imgSrc = $liElements->each(function (Crawler $liNode, $i) {

                // Check if the 'display' property is set to 'none' in the li element's style attribute
                $style = $liNode->attr('style');
                if (!($style && strpos($style, 'display: none;') !== false)) {
                    // The li element is visible

                    // Find the img element within the visible li element
                    $imgNode = $liNode->filter('img');


                    // Check if an img element was found
                    if ($imgNode->count() > 0) {
                        // Get the src attribute of the img element
                        $imgSrc = $imgNode->attr('src');
                        return $imgSrc;
                    }
                }
            });

            //dd($imgSrc);

            // Check if an image was found




            //dd($imageUrl);
            // add https://www.backmarket.fr/ to the image url at the beginning
            if (empty($imgSrc)) {
                // redirect to the add gift via link page
                $this->addFlash('danger', 'Le lien que vous avez saisi ne contient pas d\'image');
                return $this->redirectToRoute('add_gift_via_link', ['id' => $giftList->getId()]);
            }

            $imageUrl = 'https://www.backmarket.fr/' . $imgSrc[0];
            //dd($imageUrl);

            // Exemple d'extraction du titre de la page
            $pageTitle = $crawler->filter('.title-1')->text();
            //dd($pageTitle);

            //je verifie que le tire fait moins de 255 caractères
            if (strlen($pageTitle) > 255) {
                // je reduis la taille du titre
                $pageTitle = substr($pageTitle, 0, 20);
            }
            #dd($pageTitle);

            /* // Téléchargez l'image
            $imageContent = file_get_contents($imageUrl);

            // Générez un nom de fichier unique pour l'image
            $imageName = md5(uniqid()) . '.jpg';

            // Définissez le chemin du répertoire d'upload VichUploader
            $uploadDir = $this->getParameter('kernel.project_dir') . '/public/images/gifts';

            // Écrivez l'image téléchargée dans le répertoire d'upload
            file_put_contents($uploadDir . '/' . $imageName, $imageContent);

            // Remplissez le champ image de l'entité Gift avec le nom de fichier
            $gift->setImageName($imageName); */



            //essayer d' Extrayez le prix du produit
            try {
                $price = $crawler->filter('#__layout > div > div.min-h-screen.flex.flex-col > div.flex-grow.flex.flex-col > div > div.flex.justify-center.px-6.md\:px-7.bg-white.text-black.max-w-full.mb-7 > div > div > div.md\:w-2\/3.lg\:w-1\/2.lg\:flex-1.max-w-full > div > div > div.flex.flex-col.mb-3.md\:mb-1 > div > div.flex-grow.flex-row.hidden.items-center.justify-between.mb-5.md\:flex > div > div > div > div.flex.md\:flex-col.items-baseline.md\:items-end > h2 > div > div:nth-child(1)')->text();
            } catch (\Throwable $th) {
                $price = 0;
            }
            //dd('price', $price);

            /*  //si le prix est vide mets 0
            if (empty($price)) {
                $price = 0;
            } */
            //$price = preg_replace('/[^0-9]/', '', $price);
            $price = preg_replace('/€/', '', $price);
            $price = preg_replace('/,/', '.', $price);
            $price = floatval($price);

            //dd($price);

            //$price = intval($price);
            #dd($price);
            // Remplissez les champs du cadeau avec les données extraites

            $gift->setNom($pageTitle);
            $gift->setPrix($price);
            $gift->setGiftList($giftList);
            $gift->setName($form->get('name')->getData());
            $gift->setEmail($form->get('email')->getData());
            $gift->setStatus('RESERVER');
            $gift->setLienAchat($link);

            // Enregistrez le cadeau dans la base de données
            $entityManager->persist($gift);
            $entityManager->flush();

            // Redirigez l'utilisateur vers la liste de cadeaux
            return $this->redirectToRoute('front_app_gift_list_show', ['id' => $giftList->getId()]);
        }

        return $this->render('front/gift/add_via_link.html.twig', [
            'gift' => $gift,
            'form' => $form->createView(),
        ]);
    }

    #[Route('/new/{id}', name: 'app_gift_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, GiftList $giftList, UploaderHelper $uploaderHelper, Security $security, UrlGeneratorInterface $urlGenerator): Response
    {
        $giftList = $entityManager->getRepository(GiftList::class)->find($giftList);
        $gift = new Gift();
        $form = $this->createForm(GiftType::class, $gift);
        $form->handleRequest($request);

        // Check if the user is authenticated before accessing their data
        if ($security->getUser()) {
            // Get the current user's ID
            $user = $security->getUser();
            $userId = $user->getId();
            $gift->setCreatedBy($userId);

src/Controller/Front/ProfileController.php
<?php

namespace App\Controller\Front;

use App\Entity\User;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Form\UserCredentialsType;
use App\Form\UserEditType;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Doctrine\ORM\EntityManagerInterface;

#[Route('/profile')]
class ProfileController extends AbstractController
{
    #[Route('/', name: 'app_profile_default')]
    public function index(Request $request): Response
    {
        return $this->render('front/profile/default.html.twig', []);
    }

    #[Route('/edit-user', name: 'app_profile_edit_user')]
    public function editUser(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = $this->getUser();
        $form = $this->createForm(UserEditType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('front_app_profile_default');
        }

        return $this->render('front/profile/edit-user.html.twig', [
            'editUserForm' => $form->createView(),
        ]);
    }

    #[Route('/edit-credentials', name: 'app_profile_edit_credentials')]
    public function editCredentials(Request $request, EntityManagerInterface $entityManager, UserPasswordHasherInterface $userPasswordHasher): Response
    {
        $user = new User();
        $form = $this->createForm(UserCredentialsType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $user1 = $this->getUser();
            $user1->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('password')->getData()
                )
            );

            $entityManager->persist($user1);
            $entityManager->flush();

            return $this->redirectToRoute('front_app_profile_default');
        }

        return $this->render('front/profile/edit-credentials.html.twig', [
            'editCredentialsForm' => $form->createView(),
        ]);
    }

    #[Route('/termine', name: 'app_default_finish')]
    public function test(Request $request): Response
    {
        return $this->render('front/default/finish.html.twig');
    }
}

templates/front/gift/_delete_form.html.twig
<form method="post" action="{{ path('front_app_gift_delete', {'id': gift.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ gift.id) }}">
    <button class="btn">Delete</button>
</form>

templates/front/gift/_form.html.twig
<section class="section-form">
    <div class="form-connexion">


    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}

    </div>
</section>

templates/front/gift/add_via_link.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}Nouveau cadeau{% endblock %}

{% block body %}
<section class="section-form">
    <div class="form-connexion">
<h1>Ajouter un cadeau</h1>

{{ form_start(form) }}
{{ form_widget(form) }}


{{ form_end(form) }}
        </div>
</section>


{% endblock %}

templates/front/gift/confirmation_gift.html.twig
<div class="container">
    <div class="header">
        <h2 class="title">Il y a de nouveaux cadeaux dans votre liste ! : {{giftList.titre}}</h1>
    </div>
    <div class="content">
        <p>Bonjour, {{user.nom}} </p>
        <p> {{gift.name}} Il vient d'ajouter un cadeau dans votre liste. : {{giftList.titre}}<p>

        <br>
        cordialement,
        <br>
        L'equipe de GiftPlanner 

    </div>
</div>

templates/front/gift/dereservation_gift.html.twig
<div class="container">
    <div class="header">
        <h2 class="title">DÉRÉSERVATION DU CADEAUX</h1>
    </div>
    <div class="content">
        <p>Bonjour, {{user.nom}}</p>
        <p> {{gift.name}} votre cadeau vient d'être déréservé de la liste : {{giftList.titre}}<p>
        <br>

        <p>Un e-mail a été envoyé au créateur de la liste   </p>

        <br>
        Cordialement,
        <br>
        L'equipe de GiftPlanner 
        
    </div>
</div>

templates/front/gift/edit.html.twig
{% extends 'base_front.html.twig' %}
{% block title %}Modifier le cadeau{% endblock %}

{% block body %}

<section class="section-form">
    <div class="form-connexion">
        <h1>Edit Gift</h1>

        <div class="flex space-between">
            <div>
                <button>
                <a href="{{ path('front_app_gift_index') }}">back to list</a>
            </button>
            </div>
            
            <div>
                {{ include('front/gift/_delete_form.html.twig') }}
            </div>
            
        </div>
{{ include('front/gift/_form.html.twig', {'button_label': 'Update'}) }}


    </div>
</section>
{% endblock %}

templates/front/gift/index.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}Tout les cadeaux{% endblock %}

{% block body %}



<section class="section_tableau">
    {% for message in app.flashes('danger') %}
    <div class="alert alert-success">
        {{ message }}
    </div>
    {% endfor %} 
    <div class="content">
        <h1>Touts les Cadeaux</h1>
        <table>
            <thead>
                <tr>
                    <th>Nom </th>
                    <th>Prix</th>
                    <th>Image</th>
                    
                    <th>status</th>
                    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_USER')  %}
                     <th>actions</th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for gift in gifts %}
                <tr>
                    <td>{{gift.nom}}</td>
                    <td>{{gift.prix}}</td>
                    <td>{% if vich_uploader_asset(gift, 'imageFile') is null %}
                            <img height="100px" width="100px" src="{{ asset('img/gift_box.jpg') }}">
                        {% else %}
                            <img height="100px" width="100px" src="{{ vich_uploader_asset(gift, 'imageFile') }}" alt="" srcset="">
                        {% endif %}
                    </td>
                   
                    <td>
                        {% if gift.lienAchat  == 0 %}
                            <p>pas de lien</p>
                        {% else %}
                            <p >{{ gift.lienAchat }}</p>
                        {% endif %}
                    </td>
                    {% if is_granted('ROLE_ADMIN') or is_granted('ROLE_USER')%}
                    <td class="actions">
                        <a href="{{ path('front_app_gift_show', {'id': gift.id}) }}">
                            <button>
                            show
                            </button>
                        </a>
                        <a href="{{ path('front_app_gift_edit', {'id': gift.id}) }}">
                            <button>
                            edit
                        </button>
                        </a>
                    </td>
                    {% endif %}
                </tr>
                {% else %}
                <tr>
                    <td colspan="7">no records found</td>
                </tr>
                {% endfor %}
                
                <!-- Ajoutez d'autres lignes pour chaque liste de cadeaux -->
            </tbody>
        </table>
    </div>
</section>

{# <a href="{{ path('front_app_gift_new') }}">Create new</a> #}
{% endblock %}

templates/front/gift/new.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}Nouveau cadeau {% endblock %}

{% block body %}
<div class="flex flex-center">
    <h1>Ajouter un cadeau </h1>
</div>


<div class="flex flex-center">
    <h2>
        <a href="{{path('front_add_gift_via_link',{'id': gift_list.id} )}}">Ajouter un cadeau avec son lien</a>
    </h2>
</div>


<div class="flex flex-center">
    <button>
    <a href="{{ path('front_app_gift_index') }}">back to list</a>
    </button>
</div>


{{ include('front/gift/_form.html.twig') }}



{% endblock %}

templates/front/gift/remove_gift_mail.html.twig
<div class="container">
    <div class="header">
        <h2 class="title">Confirmation ajout de cadeaux</h1>
    </div>
    <div class="content">
        <p>Bonjour, {{gift.name}}</p>
        <p> {{gift.name}} votre cadeau viens d'etre ajouter à la liste  {{giftList.titre}}<p>
        <br>

        <p>vous avez la possibilité de le retirer au lien suivant : </p>
        <a href="{{ urlCancel }}">Annuler la réservation</a>

        <br>
        cordialement,
        <br>
        L'equipe de GiftPlanner 
        
    </div>
</div>

templates/front/gift/show.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}Gift{% endblock %}


{% block body %}


<section class="section_tableau">
    <div class="content">
<table class="table">
    <tbody>
        <h1 class="flex flex-center">Voici le cadeaux</h1>
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Prix</th>
            <th>
                image
            </th>
            <th>Lien_achat</th>
            <th>Status</th>
            <th>actions</th>
            
        </tr>

        <tr>
            <td>{{ gift.id }}</td>
            <td>{{ gift.nom }}</td>
            <td>{{ gift.prix }}</td>
            <td>
   
            {% if vich_uploader_asset(gift, 'imageFile') is null %}
                <img height="100px" width="100px" src="{{ asset('img/gift_box.jpg') }}">
            {% else %}
                <img height="100px" width="100px" src="{{ vich_uploader_asset(gift, 'imageFile') }}" alt="" srcset="">
            {% endif %}
        </td>
            <td>
                {% if gift.lienAchat is null %}
                <p>pas de lien</p>
            {% else %}
                <p>{{ gift.lienAchat }}</p>
            {% endif %}
            </td>
            <td>{{ gift.status }}</td>
            <td><a href="{{ path('front_app_gift_index') }}">back to list</a>

                <a href="{{ path('front_app_gift_edit', {'id': gift.id}) }}">edit</a>
                {{ include('front/gift/_delete_form.html.twig') }}
            </td>
        </tr>

    </tbody>
</table>

    </div>
</section>

{% endblock %}

templates/front/gift/status.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}Gift{% endblock %}


{% block body %}

<section class="section-form">
    <div class="form-connexion">


    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn">{{ button_label|default('Save') }}</button>
    {{ form_end(form) }}

    </div>
</section>

{% endblock %}